//! Library thumbnails, generated by the emulator itself.
//!
//! No external artwork database: a game's thumbnail is a real frame of that
//! game, produced by running the ROM headless — the exact path
//! `--headless --frames N --dump-frame` already takes — and writing the raw
//! 256x224 framebuffer as a PNG. The result is cached in
//! `<os config dir>/Prisme/Thumbnails/<game id>.png` and only ever regenerated
//! when that file is missing, so the cost is paid once per game.
//!
//! **Which frame.** A single fixed frame is a bad bet: at any given instant a
//! game may be mid-fade, on a black boot screen or on a publisher logo. So the
//! run captures several candidates (`CAPTURE_FRAMES`) and keeps the most
//! informative one, scored by `score_frame`.
//!
//! The candidate list was measured, not guessed — non-black share and score of
//! every 150th frame of the seven cartridges in `roms/` (all PAL, 50 Hz, so
//! frame 600 is 12 s of console time):
//!
//! | Game | 600 | 900 | 1200 | 1800 |
//! |---|---|---|---|---|
//! | Super Mario All-Stars + World | **100 %** | 100 % | 100 % | 47 % |
//! | Super Mario Kart | **99 %** | 99 % | 99 % | 99 % |
//! | Super Mario RPG | 100 % | **100 %** | 58 % | 6 % |
//! | Yoshi's Island | 66 % | 66 % | 66 % | 66 % |
//! | Mega Man X3 | 0 % | **66 %** | 67 % | 67 % |
//! | Secret of Mana | 6 % | 7 % | 8 % | **22 %** |
//! | Secret of Evermore | 5 % | 11 % | 9 % | **14 %** |
//!
//! Frame 600 (the count the project's own M3/M4 gate uses to reach the All-Stars
//! selection screen) is right for the majority, but three of the seven are
//! still in a dark intro there — Mega Man X3 is *exactly* on a black fade —
//! and two games have already left their title screen for an attract-mode demo
//! by 1800. No single frame works, which is why the best of
//! `[600, 900, 1200, 1800]` is kept. A run stops early as soon as a candidate
//! reaches `GOOD_ENOUGH_SCORE`, so the common case still costs one 600-frame
//! run instead of an 1800-frame one.
//!
//! Generation runs on the library thread (`library::Worker`), never on the UI
//! thread: 600 frames take about 2 s in a release build (measured on Secret of
//! Mana), and a debug build is an order of magnitude slower.

use std::path::{Path, PathBuf};

use snes_core::{Cartridge, JoypadState, Snes, SCREEN_HEIGHT, SCREEN_WIDTH};

/// Folder holding the generated thumbnails, inside the app's config directory.
pub const THUMB_DIR: &str = "Thumbnails";

/// Frames at which a candidate picture is captured; the last one is also the
/// longest the emulation run can be (see module docs for how these were
/// chosen).
pub const CAPTURE_FRAMES: &[u32] = &[600, 900, 1200, 1800];

/// A candidate scoring at least this much ends the run: the picture is already
/// a full, colourful screen and emulating further could only walk into an
/// attract-mode demo. Measured references: the All-Stars selection screen
/// scores 5.5 M at frame 600 and Super Mario Kart's title 2.9 M, while a dark
/// intro frame stays under 0.5 M.
const GOOD_ENOUGH_SCORE: u64 = 1_000_000;

/// A channel value at or below this counts as black: the SNES fades to a
/// non-zero but very dark colour on its way out, and such a frame carries no
/// more information than a black one.
const BLACK_LEVEL: u8 = 16;

/// Directory the thumbnails live in, or `None` when there is no config
/// directory (no `$HOME`/`%APPDATA%`).
pub fn thumb_dir() -> Option<PathBuf> {
    crate::prefs::data_path(THUMB_DIR)
}

/// Cached thumbnail path of a game. `id` comes from `library::game_id`, which
/// is built from `sanitize_file_stem` + a hex checksum, so it is always a
/// usable file name.
pub fn thumb_path(id: &str) -> Option<PathBuf> {
    thumb_dir().map(|d| d.join(format!("{id}.png")))
}

/// How informative a captured frame is: the number of non-black pixels times
/// the number of distinct colours in it. A black or single-colour screen
/// scores 0 or nearly 0; a title screen, with hundreds of colours over most of
/// the picture, scores orders of magnitude higher. Colours are counted at the
/// SNES's own 5-5-5 precision, so the count is exact rather than approximate.
pub fn score_frame(rgba: &[u8]) -> u64 {
    // One bit per 15-bit BGR555 colour: 32768 bits = 512 u64 words.
    let mut seen = [0u64; 512];
    let mut non_black: u64 = 0;
    let mut distinct: u64 = 0;
    for px in rgba.chunks_exact(4) {
        let (r, g, b) = (px[0], px[1], px[2]);
        if r > BLACK_LEVEL || g > BLACK_LEVEL || b > BLACK_LEVEL {
            non_black += 1;
        }
        let key = ((r as usize >> 3) << 10) | ((g as usize >> 3) << 5) | (b as usize >> 3);
        let (word, bit) = (key / 64, key % 64);
        if seen[word] & (1 << bit) == 0 {
            seen[word] |= 1 << bit;
            distinct += 1;
        }
    }
    non_black * distinct
}

/// Emulate `rom` headless and write its thumbnail to `out` (atomically, so an
/// interrupted run never leaves a truncated PNG behind).
///
/// The picture is the raw 256x224 framebuffer, exactly like `--dump-frame`: no
/// zoom, no filter, no overlay. Input is never pressed — the intent is the
/// game's own attract sequence, not a started game.
pub fn generate(rom: &Path, out: &Path) -> Result<(), String> {
    let bytes = crate::load_rom_bytes(rom)?;
    let cart = Cartridge::from_bytes(bytes)?;
    let mut snes = Snes::new(cart);

    let total = CAPTURE_FRAMES.iter().copied().max().unwrap_or(0);
    let mut best: Option<(u64, Vec<u8>)> = None;
    let mut rgba = vec![0u8; SCREEN_WIDTH * SCREEN_HEIGHT * 4];
    for frame in 1..=total {
        snes.run_frame([JoypadState::default(), JoypadState::default()]);
        if !CAPTURE_FRAMES.contains(&frame) {
            continue;
        }
        snes.framebuffer.to_rgba(&mut rgba);
        let score = score_frame(&rgba);
        if best.as_ref().is_none_or(|(best_score, _)| score > *best_score) {
            best = Some((score, rgba.clone()));
        }
        if score >= GOOD_ENOUGH_SCORE {
            break;
        }
    }
    let (_, picture) = best.ok_or_else(|| "no frame captured".to_string())?;
    let png = crate::encode_rgba_png(&picture, SCREEN_WIDTH as u32, SCREEN_HEIGHT as u32)?;
    crate::atomic::write(out, &png)
}

/// Decode a PNG written by this application (8-bit RGBA, no interlacing) into
/// `(width, height, rgba)`. Used by the UI to upload thumbnails and
/// screenshots as textures.
pub fn decode_png(path: &Path) -> Result<(u32, u32, Vec<u8>), String> {
    let file =
        std::fs::File::open(path).map_err(|e| format!("open {}: {e}", path.display()))?;
    let decoder = png::Decoder::new(std::io::BufReader::new(file));
    let mut reader = decoder.read_info().map_err(|e| format!("png {}: {e}", path.display()))?;
    let mut buf = vec![0u8; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).map_err(|e| format!("png {}: {e}", path.display()))?;
    buf.truncate(info.buffer_size());
    let rgba = match info.color_type {
        png::ColorType::Rgba => buf,
        png::ColorType::Rgb => {
            let mut out = Vec::with_capacity(info.width as usize * info.height as usize * 4);
            for px in buf.chunks_exact(3) {
                out.extend_from_slice(&[px[0], px[1], px[2], 0xFF]);
            }
            out
        }
        other => return Err(format!("{}: unsupported PNG color type {other:?}", path.display())),
    };
    Ok((info.width, info.height, rgba))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn frame(fill: impl Fn(usize) -> [u8; 4]) -> Vec<u8> {
        let mut out = vec![0u8; SCREEN_WIDTH * SCREEN_HEIGHT * 4];
        for (i, px) in out.chunks_exact_mut(4).enumerate() {
            px.copy_from_slice(&fill(i));
        }
        out
    }

    #[test]
    fn a_black_frame_scores_zero() {
        let black = frame(|_| [0, 0, 0, 255]);
        assert_eq!(score_frame(&black), 0);
        // A very dark fade frame counts as black too (BLACK_LEVEL).
        let almost = frame(|_| [8, 8, 8, 255]);
        assert_eq!(score_frame(&almost), 0);
    }

    #[test]
    fn a_busy_frame_scores_higher_than_a_flat_one() {
        let flat = frame(|_| [0, 0, 255, 255]);
        let busy = frame(|i| [(i % 251) as u8, (i % 173) as u8, (i % 97) as u8, 255]);
        assert!(score_frame(&flat) > 0);
        assert!(
            score_frame(&busy) > score_frame(&flat),
            "busy {} vs flat {}",
            score_frame(&busy),
            score_frame(&flat)
        );
        // A single flat colour is exactly (pixels * 1 colour).
        assert_eq!(score_frame(&flat), (SCREEN_WIDTH * SCREEN_HEIGHT) as u64);
    }

    #[test]
    fn colours_are_counted_at_the_snes_5_bit_precision() {
        // Two RGB888 values that map to the same BGR555 colour count once.
        let f = frame(|i| if i % 2 == 0 { [8, 0, 0, 255] } else { [9, 0, 0, 255] });
        // 0x08 >> 3 == 0x09 >> 3 == 1, and 8 <= BLACK_LEVEL so nothing is lit.
        assert_eq!(score_frame(&f), 0);
        let f = frame(|i| if i % 2 == 0 { [200, 0, 0, 255] } else { [201, 0, 0, 255] });
        assert_eq!(score_frame(&f), (SCREEN_WIDTH * SCREEN_HEIGHT) as u64);
    }

    #[test]
    fn capture_frames_start_at_the_gate_count_and_only_grow() {
        assert!(CAPTURE_FRAMES.windows(2).all(|w| w[0] < w[1]), "{CAPTURE_FRAMES:?}");
        // Frame 600 is the M3/M4 gate count; anything earlier is still in the
        // boot sequence of most cartridges (see the module's measurements).
        assert_eq!(CAPTURE_FRAMES[0], 600);
        assert_eq!(*CAPTURE_FRAMES.last().unwrap(), 1800);
        assert!(CAPTURE_FRAMES.len() >= 2, "one candidate cannot dodge a black screen");
        // The early-exit threshold must sit between a dark intro frame and a
        // real title screen, or it would either never fire or fire on a fade.
        assert!((500_000..3_000_000).contains(&GOOD_ENOUGH_SCORE));
    }

    #[test]
    fn thumbnail_paths_are_one_png_per_game_id() {
        let Some(dir) = thumb_dir() else { return }; // no HOME in this environment
        assert!(dir.ends_with(THUMB_DIR));
        let a = thumb_path("SUPER_MARIOWORLD-A0DA").expect("path");
        let b = thumb_path("SUPER_MARIOWORLD-A0DB").expect("path");
        assert_ne!(a, b);
        assert_eq!(a.extension().unwrap(), "png");
        assert_eq!(a.parent().unwrap(), dir);
    }

    /// End-to-end generation on a real cartridge. Ignored by default: it
    /// emulates `CAPTURE_FRAMES.last()` frames, which takes seconds in a
    /// release build and minutes in a debug one, and it needs the ROM.
    /// Run with `cargo test -p prisme --release -- --ignored thumbnail`.
    #[test]
    #[ignore]
    fn generates_a_real_thumbnail_from_a_real_rom() {
        let rom = Path::new("../roms/Secret of Mana (F).zip");
        let rom = if rom.is_file() { rom } else { Path::new("roms/Secret of Mana (F).zip") };
        assert!(rom.is_file(), "ROM fixture missing: {}", rom.display());
        let dir = std::env::temp_dir()
            .join(format!("prisme_thumb_{}_{}", std::process::id(), "e2e"));
        std::fs::create_dir_all(&dir).expect("mkdir");
        let out = dir.join("game.png");
        generate(rom, &out).expect("generate");
        let (w, h, rgba) = decode_png(&out).expect("decode");
        assert_eq!((w, h), (SCREEN_WIDTH as u32, SCREEN_HEIGHT as u32));
        // The whole point of scoring candidates: never ship a black picture.
        assert!(score_frame(&rgba) > 0, "the chosen frame is black");
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn a_written_png_decodes_back_to_the_same_pixels() {
        let dir = std::env::temp_dir()
            .join(format!("prisme_thumb_{}_{}", std::process::id(), "roundtrip"));
        std::fs::create_dir_all(&dir).expect("mkdir");
        let path = dir.join("t.png");
        let picture = frame(|i| [(i % 256) as u8, 0, 128, 255]);
        let png = crate::encode_rgba_png(&picture, SCREEN_WIDTH as u32, SCREEN_HEIGHT as u32)
            .expect("encode");
        crate::atomic::write(&path, &png).expect("write");
        let (w, h, back) = decode_png(&path).expect("decode");
        assert_eq!((w, h), (SCREEN_WIDTH as u32, SCREEN_HEIGHT as u32));
        assert_eq!(back, picture);
        assert!(decode_png(&dir.join("absent.png")).is_err());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
